# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9788188af9758fa90860b5bca491e64946ba44579bb30e802edb573c2d7a1075c13347555ae207b5bb5a18d433b8330d695a780f07e611d2a819021d12ab071f

test:
  secret_key_base: 5a8ba864af398b8d71dc9e0dec01cf76a83db6377b4f1112c7216ddfb02f960479945fa9720532602fa9049f4def175719000a1c87eddefa8201fbdefe0f3940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
